-- migrate:up
create table media_link (
  id int generated by default as identity primary key,
  media_id integer not null unique,
  resource_id integer not null,
  resource_type text not null
);

create index media_link_media_id_idx on public.media_link (media_id);

create index media_link_resource_id_resource_type_idx on public.media_link (resource_id, resource_type);

-- migrate:down
drop table media_link;
