-- migrate:up

create type provenance as enum (
  'garden',
  'wild',
  'garden_wild_origin',
  'uncertain'
);

create table supplier (
  id int not null generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  street_address text,
  street_address2 text,
  city text,
  province text,
  postal_code text,
  country text
);

alter table accession
add column provenance provenance not null default 'uncertain',
add column supplier_id int constraint accession_supplier_id_fkey references supplier (id);

create table collection (
  id int not null generated by default as identity primary key,
  collected_date timestamptz,
  collector text,
  habitat text,
  taxa text,
  remarks text,
  country text,
  province text,
  locality text,
  geo_coordinates geography(POINT),
  gps_datum text,
  -- TODO: constraint for positive value
  geo_uncertainty smallint,
  -- TODO: constraint for positive value
  elevation smallint,
  accession_id int unique constraint supplier_accession_id_fkey references accession (id) on delete cascade
)


-- migrate:down

drop table collection;

alter table accession
drop column supplier_id,
drop column provenance;

drop type provenance;

drop table supplier;
