-- migrate:up

-- TODO:
-- accession.id_qualifier
-- accession.id_qualifier_rank
-- accession.private
-- accession.provenance
-- accession.wild_provenance_status

-- accession.propagation_id
-- accession.plant_propagation_id
-- accession.collection_id
-- accession.donor_id
--

create type id_qualifier as enum (
  'aff',
  'cf',
  'forsan',
  'incorrect',
  'near',
  'questionable'
);

create type id_qualifier_rank as enum (
  'below_family',
  'family',
  'genus',
  'species',
  'first_infraspecific_epithet',
  'second_infraspecific_epithet',
  'cultivar'
);

create type provenance_type as enum (
 'wild',
 'cultivated',
 'not_wild',
 'purchase',
 'insufficient_data'
);

create type wild_provenance_status as enum (
 'wild_native',
 'wild_non_native',
 'cultivated_native',
 'cultivated'
 'not_wild'
 'purchase'
 'insufficient_data'
);

alter table accession
add column private boolean not null default false,
add column id_qualifier id_qualifier,
add column id_qualifier_rank id_qualifier_rank,
add column provenance_type provenance_type,
add column wild_provenance_status wild_provenance_status;

create type source_type as enum (
  'expedition',
  'gene_bank',
  'field_station',
  'staff',
  'university_department',
  'club',
  'municipal_department',
  'commerical',
  'individual',
  'other'
);

create table source_detail (
  id int generated by default as identity primary key,
  name text,
  description text,
  phone text,
  email text,
  address text,
  source_type source_type
);

create table source (
  id int generated by default as identity primary key,
  sources_code text,
  accession_id int constraint source_accession_id_fkey unique references accession (id) not null,
  source_detail_id int constraint source_detail_id_fkey references source_detail (id) not null
);


create table collection (
  id int generated by default as identity primary key,
  collector text,
  collectors_code text,
  date date,
  locale text,
  -- Always store points as WGS84 but allow setting a coordinate system for conversion
  coordinates geography (point, 4326),
  coordinates_accuracy smallint,
  -- Use postgis_srs_all to get all of the coordinate systems
  coordinate_system_srid text,
  altitude smallint,
  altitude_accuracy smallint,
  notes text,
  source_id int constraint collection_source_id_fkey unique references source (id) not null
);


-- migrate:down
