(ns sepal.app.routes.accession.routes)

(def index ::index)
(def new ::new)
(def next-code ::next-code)
(def provenance-suggestion ::provenance-suggestion)
(def detail ::detail)
(def detail-general ::detail-general)
(def detail-collection ::detail-collection)
(def detail-media ::detail-media)
(def detail-notes ::detail-notes)
(def detail-note ::detail-note)
(def detail-tags ::detail-tags)
(def detail-tag ::detail-tag)
(def export ::export)
(def delete ::delete)
(def detail-collection-delete ::detail-collection-delete)

(def panel ::panel)

