(ns sepal.app.routes.taxon.routes)

(def index ::index)
(def new ::new)
(def rank-guess ::rank-guess)
(def parent-suggestion ::parent-suggestion)
(def parentage-row ::parentage-row)
(def detail ::detail)
(def detail-name ::detail-name)
(def detail-media ::detail-media)
(def detail-synonyms ::detail-synonyms)
(def detail-synonym ::detail-synonym)
(def detail-notes ::detail-notes)
(def detail-note ::detail-note)
(def detail-tags ::detail-tags)
(def detail-tag ::detail-tag)
(def export ::export)

(def panel ::panel)
(def delete ::delete)
