(ns sepal.app.routes.location.routes)

(def index ::index)
(def new ::new)
(def detail ::detail)
(def detail-general ::detail-general)
(def detail-observations ::detail-observations)
(def detail-media ::detail-media)
(def detail-observation ::detail-observation)
(def export ::export)

(def panel ::panel)
(def delete ::delete)
(def archive ::archive)
(def unarchive ::unarchive)
