"""add accessions

Revision ID: 2987d8e7028f
Revises: a1e6729622a6
Create Date: 2022-08-04 06:39:18.173305

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2987d8e7028f"
down_revision = "a1e6729622a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accession",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("taxon_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["taxon_id"],
            ["taxon.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accession_item",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("accession_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accession_id"],
            ["accession.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accession_item")
    op.drop_table("accession")
    # ### end Alembic commands ###
