"""initial migrations

Revision ID: 4957f993066b
Revises:
Create Date: 2022-07-28 06:25:42.250906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4957f993066b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("abbreviation", sa.Text(), server_default="", nullable=False),
        sa.Column("short_name", sa.Text(), server_default="", nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("postal_code", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "organization_user",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "read", "write", name="organization_role"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "role",
            name="organization_id_user_id_role_idx",
        ),
    )
    op.create_table(
        "taxon",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "rank",
            sa.Enum(
                "class",
                "family",
                "form",
                "genus",
                "kingdom",
                "order",
                "phylum",
                "section",
                "series",
                "species",
                "subclass",
                "subfamily",
                "subform",
                "subgenus",
                "subsection",
                "subseries",
                "subspecies",
                "subtribe",
                "subvariety",
                "superorder",
                "tribe",
                "variety",
                name="taxon_rank",
            ),
            nullable=False,
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["taxon.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("taxon")
    op.drop_table("organization_user")
    op.drop_table("user")
    op.drop_table("organization")
    op.execute("drop type organization_role")
    op.execute("drop type taxon_rank")
    # ### end Alembic commands ###
