"""add organization settings column

Revision ID: 521a30adac33
Revises: ecd0e389090d
Create Date: 2023-01-31 07:24:45.491919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '521a30adac33'
down_revision = 'ecd0e389090d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('settings')

    # ### end Alembic commands ###
