"""add accept invitation columns

Revision ID: 54274de8b1af
Revises: acb87fb9e89a
Create Date: 2023-03-24 14:45:50.950357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54274de8b1af"
down_revision = "acb87fb9e89a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invitation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("rejected_by", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("accepted_by", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("invitation_accepted_by_user_fk"),
            "user",
            ["accepted_by"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("invitation_rejected_by_user_fk"),
            "user",
            ["rejected_by"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invitation", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("invitation_rejected_by_user_fk"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("invitation_accepted_by_user_fk"), type_="foreignkey"
        )
        batch_op.drop_column("accepted_by")
        batch_op.drop_column("accepted_at")
        batch_op.drop_column("rejected_by")
        batch_op.drop_column("rejected_at")

    # ### end Alembic commands ###
