"""add activity table

Revision ID: 6695940c4f13
Revises: d3ebfca9e6ed
Create Date: 2022-12-24 08:12:05.555470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6695940c4f13"
down_revision = "d3ebfca9e6ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "accession_event",
                "accession_item_event",
                "location_event",
                "media_event",
                "organization_event",
                "taxon_event",
                "user_event",
                name="activity_type",
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("activity_organization_id_organization_fk"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("activity_user_id_user_fk")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("activity_pk")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity")
    # ### end Alembic commands ###
