"""update accession items and add unique contraints

Revision ID: 68834eb197ed
Revises: 2987d8e7028f
Create Date: 2022-08-06 07:32:33.642122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68834eb197ed"
down_revision = "2987d8e7028f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "accession_organization_id_code_idx", "accession", ["organization_id", "code"]
    )
    op.add_column(
        "accession_item", sa.Column("location_id", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(
        "accession_item_organization_id_accession_id_code_idx",
        "accession_item",
        ["organization_id", "accession_id", "code"],
    )
    op.create_foreign_key(None, "accession_item", "location", ["location_id"], ["id"])
    op.drop_constraint("organization_id_code_idx", "location", type_="unique")
    op.drop_constraint("organization_id_name_idx", "location", type_="unique")
    op.create_unique_constraint(
        "location_organization_id_code_idx", "location", ["organization_id", "code"]
    )
    op.create_unique_constraint(
        "location_organization_id_name_idx", "location", ["organization_id", "name"]
    )
    op.drop_constraint(
        "organization_id_user_id_role_idx", "organization_user", type_="unique"
    )
    op.create_unique_constraint(
        "organization_user_organization_id_user_id_role_idx",
        "organization_user",
        ["organization_id", "user_id", "role"],
    )
    op.create_unique_constraint(
        "taxon_organization_id_name_author_rank_idx",
        "taxon",
        ["organization_id", "name", "author", "rank"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "taxon_organization_id_name_author_rank_idx", "taxon", type_="unique"
    )
    op.drop_constraint(
        "organization_user_organization_id_user_id_role_idx",
        "organization_user",
        type_="unique",
    )
    op.create_unique_constraint(
        "organization_id_user_id_role_idx",
        "organization_user",
        ["organization_id", "user_id", "role"],
    )
    op.drop_constraint("location_organization_id_name_idx", "location", type_="unique")
    op.drop_constraint("location_organization_id_code_idx", "location", type_="unique")
    op.create_unique_constraint(
        "organization_id_name_idx", "location", ["organization_id", "name"]
    )
    op.create_unique_constraint(
        "organization_id_code_idx", "location", ["organization_id", "code"]
    )
    op.drop_constraint(None, "accession_item", type_="foreignkey")
    op.drop_constraint(
        "accession_item_organization_id_accession_id_code_idx",
        "accession_item",
        type_="unique",
    )
    op.drop_column("accession_item", "location_id")
    op.drop_constraint(
        "accession_organization_id_code_idx", "accession", type_="unique"
    )
    # ### end Alembic commands ###
