"""add created_by columns

Revision ID: acb87fb9e89a
Revises: 521a30adac33
Create Date: 2023-02-04 09:46:53.642494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb87fb9e89a'
down_revision = '521a30adac33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('accession_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('taxon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('taxon', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('accession_item', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('accession', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
