SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: wfo_plantlist_2023_12; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA wfo_plantlist_2023_12;


--
-- Name: moddatetime; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS moddatetime WITH SCHEMA public;


--
-- Name: EXTENSION moddatetime; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION moddatetime IS 'functions for tracking last modification time';


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: material_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.material_status_enum AS ENUM (
    'dead',
    'alive'
);


--
-- Name: material_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.material_type_enum AS ENUM (
    'plant',
    'seed',
    'vegetative',
    'tissue',
    'other'
);


--
-- Name: organization_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.organization_role AS ENUM (
    'owner',
    'admin',
    'read',
    'write',
    'guest'
);


--
-- Name: taxon_rank_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.taxon_rank_enum AS ENUM (
    'class',
    'family',
    'form',
    'genus',
    'kingdom',
    'order',
    'phylum',
    'prole',
    'section',
    'series',
    'species',
    'subclass',
    'subfamily',
    'subkingdom',
    'subform',
    'subgenus',
    'subsection',
    'subseries',
    'subspecies',
    'subtribe',
    'subvariety',
    'superorder',
    'tribe',
    'variety'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accession; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accession (
    id integer NOT NULL,
    code text NOT NULL,
    taxon_id integer NOT NULL,
    organization_id integer NOT NULL
);


--
-- Name: accession_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity (
    id integer NOT NULL,
    data jsonb NOT NULL,
    type text NOT NULL,
    organization_id integer NOT NULL,
    created_by integer NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL
);


--
-- Name: activity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.location (
    id integer NOT NULL,
    code text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    organization_id integer NOT NULL
);


--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: material; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.material (
    id integer NOT NULL,
    code text NOT NULL,
    accession_id integer NOT NULL,
    location_id integer NOT NULL,
    organization_id integer NOT NULL,
    type public.material_type_enum DEFAULT 'plant'::public.material_type_enum NOT NULL,
    status public.material_status_enum DEFAULT 'alive'::public.material_status_enum NOT NULL,
    memorial boolean DEFAULT false NOT NULL,
    quantity integer DEFAULT 1 NOT NULL
);


--
-- Name: material_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.material ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.material_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media (
    id integer NOT NULL,
    s3_bucket text NOT NULL,
    s3_key text NOT NULL,
    title text,
    description text,
    size_in_bytes integer NOT NULL,
    media_type text NOT NULL,
    organization_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer NOT NULL
);


--
-- Name: media_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_link; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media_link (
    id integer NOT NULL,
    media_id integer NOT NULL,
    resource_id integer NOT NULL,
    resource_type text NOT NULL
);


--
-- Name: media_link_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.media_link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organization; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization (
    id integer NOT NULL,
    abbreviation text,
    name text NOT NULL,
    short_name text
);


--
-- Name: organization_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organization ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organization_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_user (
    organization_id integer NOT NULL,
    user_id integer NOT NULL,
    role public.organization_role NOT NULL
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying(128) NOT NULL
);


--
-- Name: taxon; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.taxon (
    id integer NOT NULL,
    name text NOT NULL,
    author text,
    organization_id integer,
    parent_id integer,
    rank public.taxon_rank_enum NOT NULL,
    wfo_taxon_id_2023_12 text
);


--
-- Name: taxon_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.taxon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.taxon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    avatar_public_id text,
    email text NOT NULL,
    password text NOT NULL,
    email_verified_at timestamp with time zone
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: name; Type: TABLE; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE TABLE wfo_plantlist_2023_12.name (
    id text,
    alternative_id text,
    basionym_id text,
    scientific_name text,
    authorship text,
    rank text,
    uninomial text,
    genus text,
    infrageneric_epithet text,
    specific_epithet text,
    infraspecific_epithet text,
    code text,
    reference_id text,
    published_in_year text,
    link text
);


--
-- Name: reference; Type: TABLE; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE TABLE wfo_plantlist_2023_12.reference (
    id text,
    citation text,
    link text,
    doi text,
    remarks text
);


--
-- Name: synonym; Type: TABLE; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE TABLE wfo_plantlist_2023_12.synonym (
    id text,
    taxon_id text,
    name_id text,
    according_to_id text,
    reference_id text,
    link text
);


--
-- Name: taxon; Type: TABLE; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE TABLE wfo_plantlist_2023_12.taxon (
    id text,
    name_id text,
    parent_id text,
    according_to_id text,
    scrutinizer text,
    scrutinizer_id text,
    scrutinizer_date text,
    reference_id text,
    link text
);


--
-- Name: accession accession_code_organization_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accession
    ADD CONSTRAINT accession_code_organization_id_key UNIQUE (code, organization_id);


--
-- Name: accession accession_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accession
    ADD CONSTRAINT accession_pkey PRIMARY KEY (id);


--
-- Name: location location_code_organization_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_code_organization_id_key UNIQUE (code, organization_id);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);


--
-- Name: material material_code_accession_id_organization_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT material_code_accession_id_organization_id_key UNIQUE (code, accession_id, organization_id);


--
-- Name: material material_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT material_pkey PRIMARY KEY (id);


--
-- Name: media_link media_link_media_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_link
    ADD CONSTRAINT media_link_media_id_key UNIQUE (media_id);


--
-- Name: media_link media_link_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_link
    ADD CONSTRAINT media_link_pkey PRIMARY KEY (id);


--
-- Name: media media_organization_id_s3_bucket_s3_key_unq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_organization_id_s3_bucket_s3_key_unq UNIQUE (organization_id, s3_bucket, s3_key);


--
-- Name: media media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);


--
-- Name: organization organization_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization
    ADD CONSTRAINT organization_pkey PRIMARY KEY (id);


--
-- Name: organization_user organization_user_organization_id_user_id_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_user
    ADD CONSTRAINT organization_user_organization_id_user_id_unique UNIQUE (organization_id, user_id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: taxon taxon_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.taxon
    ADD CONSTRAINT taxon_pkey PRIMARY KEY (id);


--
-- Name: user user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- Name: user user_password_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_password_key UNIQUE (password);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: accession_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accession_id_idx ON public.accession USING btree (id);


--
-- Name: accession_organization_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accession_organization_id_idx ON public.accession USING btree (organization_id);


--
-- Name: activity_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX activity_id_idx ON public.activity USING btree (id);


--
-- Name: activity_organization_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX activity_organization_id_idx ON public.activity USING btree (organization_id);


--
-- Name: location_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX location_id_idx ON public.location USING btree (id);


--
-- Name: location_organization_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX location_organization_id_idx ON public.location USING btree (organization_id);


--
-- Name: material_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX material_id_idx ON public.material USING btree (id);


--
-- Name: material_organization_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX material_organization_id_idx ON public.material USING btree (organization_id);


--
-- Name: media_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX media_id_idx ON public.media USING btree (id);


--
-- Name: media_link_media_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX media_link_media_id_idx ON public.media_link USING btree (media_id);


--
-- Name: media_link_resource_id_resource_type_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX media_link_resource_id_resource_type_idx ON public.media_link USING btree (resource_id, resource_type);


--
-- Name: media_organization_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX media_organization_id_idx ON public.media USING btree (organization_id);


--
-- Name: organization_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX organization_id_idx ON public.organization USING btree (id);


--
-- Name: taxon_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxon_id_idx ON public.taxon USING btree (id);


--
-- Name: taxon_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxon_name_idx ON public.taxon USING btree (name);


--
-- Name: taxon_name_trgm_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxon_name_trgm_idx ON public.taxon USING gist (name public.gist_trgm_ops);


--
-- Name: taxon_organization_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxon_organization_id_idx ON public.taxon USING btree (organization_id);


--
-- Name: taxon_parent_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxon_parent_id_idx ON public.taxon USING btree (parent_id);


--
-- Name: taxon_wfo_taxon_id_2023_12_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxon_wfo_taxon_id_2023_12_idx ON public.taxon USING btree (wfo_taxon_id_2023_12);


--
-- Name: user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_id_idx ON public."user" USING btree (id);


--
-- Name: name_id_idx; Type: INDEX; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE INDEX name_id_idx ON wfo_plantlist_2023_12.name USING btree (id);


--
-- Name: name_scientific_name_idx; Type: INDEX; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE INDEX name_scientific_name_idx ON wfo_plantlist_2023_12.name USING btree (scientific_name);


--
-- Name: name_scientific_name_tsvector_idx; Type: INDEX; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE INDEX name_scientific_name_tsvector_idx ON wfo_plantlist_2023_12.name USING gin (to_tsvector('english'::regconfig, scientific_name));


--
-- Name: reference_id_idx; Type: INDEX; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE INDEX reference_id_idx ON wfo_plantlist_2023_12.reference USING btree (id);


--
-- Name: synonym_id_idx; Type: INDEX; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE INDEX synonym_id_idx ON wfo_plantlist_2023_12.synonym USING btree (id);


--
-- Name: taxon_id_idx; Type: INDEX; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE INDEX taxon_id_idx ON wfo_plantlist_2023_12.taxon USING btree (id);


--
-- Name: taxon_name_id_idx; Type: INDEX; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE INDEX taxon_name_id_idx ON wfo_plantlist_2023_12.taxon USING btree (name_id);


--
-- Name: taxon_parent_id_idx; Type: INDEX; Schema: wfo_plantlist_2023_12; Owner: -
--

CREATE INDEX taxon_parent_id_idx ON wfo_plantlist_2023_12.taxon USING btree (parent_id);


--
-- Name: accession accession_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accession
    ADD CONSTRAINT accession_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


--
-- Name: accession accession_taxon_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accession
    ADD CONSTRAINT accession_taxon_id_fkey FOREIGN KEY (taxon_id) REFERENCES public.taxon(id);


--
-- Name: activity activity_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity
    ADD CONSTRAINT activity_created_by_fkey FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- Name: activity activity_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity
    ADD CONSTRAINT activity_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


--
-- Name: location location_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


--
-- Name: material material_accession_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT material_accession_id_fkey FOREIGN KEY (accession_id) REFERENCES public.accession(id);


--
-- Name: material material_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT material_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.location(id);


--
-- Name: material material_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT material_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


--
-- Name: media media_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_created_by_fkey FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- Name: media media_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


--
-- Name: organization_user organization_user_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_user
    ADD CONSTRAINT organization_user_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


--
-- Name: organization_user organization_user_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_user
    ADD CONSTRAINT organization_user_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: taxon taxon_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.taxon
    ADD CONSTRAINT taxon_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


--
-- Name: taxon taxon_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.taxon
    ADD CONSTRAINT taxon_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.taxon(id);


--
-- PostgreSQL database dump complete
--


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('20240618125844'),
    ('20240618180333'),
    ('20240723120705');
