create table public.user (
  id int generated by default as identity primary key,
  avatar_public_id text,
  email text not null unique,
  password text not null unique,
  -- email_verified_at timestamptz default null,
  created_at timestamptz default timezone('utc'::text, current_timestamp) not null,
  updated_at timestamptz default timezone('utc'::text, current_timestamp) not null
);
--;;
create trigger user_updated_at
  before update
  on public.user
  for each row execute procedure moddatetime (updated_at);
--;;
create table public.organization (
  id int generated by default as identity primary key,
  abbreviation text,
  name text not null,
  short_name text,
  created_at timestamptz default timezone('utc'::text, current_timestamp) not null,
  updated_at timestamptz default timezone('utc'::text, current_timestamp) not null
);
--;;
create trigger organization_update_updated_at
  before update
  on organization
  for each row execute procedure moddatetime (updated_at);
--;;
create type organization_role as enum (
  'owner',
  'admin',
  'read',
  'write',
  'guest'
);
--;;
create table public.organization_user (
  organization_id int constraint organization_user_organization_id_fkey references organization (id) not null,
  user_id int constraint organization_user_user_id_fkey references public.user (id) not null,
  role organization_role not null,
  created_at timestamptz default timezone('utc'::text, current_timestamp) not null,
  updated_at timestamptz default timezone('utc'::text, current_timestamp) not null
);
--;;
alter table public.organization_user
add constraint organization_user_organization_id_user_id_unique unique (organization_id, user_id);
--;;
create trigger organization_user_update_updated_at
  before update
  on organization_user
  for each row execute procedure moddatetime (updated_at);
--;;
create or replace function is_organization_member (_organization_id integer, _user_id integer)
  returns boolean
  language sql
  immutable
  as $$
  select
    exists (
      select
        1
      from
        organization_user
      where
        user_id = _user_id
        and organization_id = _organization_id
     )
$$;
--;;
create or replace function has_organization_role (_organization_id integer, _user_id integer, _roles organization_role[])
  returns boolean
  language sql
  immutable
  as $$
  select
    exists (
      select
        *
      from
        organization_user
      where
        user_id = _user_id
        and organization_id = _organization_id
        and role = any (_roles)
      limit 1)
$$;
--;;
create type public.taxon_rank_enum as enum (
  'class',
  'family',
  'form',
  'genus',
  'kingdom',
  'order',
  'phylum',
  'section',
  'series',
  'species',
  'subclass',
  'subfamily',
  'subform',
  'subgenus',
  'subsection',
  'subseries',
  'subspecies',
  'subtribe',
  'subvariety',
  'superorder',
  'tribe',
  'variety'
);
--;;
create table public.taxon (
  id int generated by default as identity primary key,
  name text not null,
  author text not null default '',
  organization_id int constraint taxon_organization_id_fkey references organization (id) not null,
  parent_id int constraint taxon_parent_id_fkey references taxon (id),
  rank public.taxon_rank_enum not null,
  created_at timestamptz default timezone('utc'::text, current_timestamp) not null,
  updated_at timestamptz default timezone('utc'::text, current_timestamp) not null
);
--;;
create table public.location (
  id int generated by default as identity primary key,
  code text not null,
  name text not null default '',
  description text not null default '',
  organization_id int constraint location_organization_id_fkey references organization (id) not null,
  created_at timestamptz default timezone('utc'::text, current_timestamp) not null,
  updated_at timestamptz default timezone('utc'::text, current_timestamp) not null
);
--;;
alter table public.location
add constraint location_code_organization_id_key unique (code, organization_id);
--;;
create table public.accession (
  id int generated by default as identity primary key,
  code text not null,
  taxon_id int constraint accession_taxon_id_fkey references taxon (id) not null,
  organization_id int constraint accession_organization_id_fkey references organization (id) not null,
  created_at timestamptz default timezone('utc'::text, current_timestamp) not null,
  updated_at timestamptz default timezone('utc'::text, current_timestamp) not null
);
--;;
alter table public.accession
add constraint accession_code_organization_id_key unique (code, organization_id);
--;;
create table public.accession_item (
  id int generated by default as identity primary key,
  code text not null,
  accession_id int constraint accession_item_accession_id_fkey references accession (id) not null,
  location_id int constraint accession_item_location_id_fkey references location (id) not null,
  organization_id int constraint accession_item_organization_id_fkey references organization (id) not null,
  created_at timestamptz default timezone('utc'::text, current_timestamp) not null,
  updated_at timestamptz default timezone('utc'::text, current_timestamp) not null
);
--;;
alter table public.accession_item
add constraint accession_item_code_accession_id_organization_id_key unique (code, accession_id, organization_id);
--;;
