(ns sepal.app.routes.org.routes)

(def accessions :org/accessions)
(def accessions-new :org/accessions-new)
(def activity :org/activity)
(def create :org/create)
(def detail :org/detail)
(def index :org/index)
(def locations :org/locations)
(def locations-new :org/locations-new)
(def materials :org/materials)
(def materials-new :org/materials-new)
(def media :org/media)
(def taxa :org/taxa)
(def taxa-new :org/taxa-new)
