(ns sepal.app.routes.material.routes)

(def index ::index)
(def new ::new)
(def next-code ::next-code)
(def detail ::detail)
(def detail-general ::detail-general)
(def detail-media ::detail-media)
(def detail-observations ::detail-observations)
(def detail-observation ::detail-observation)
(def detail-tags ::detail-tags)
(def detail-tag ::detail-tag)
(def export ::export)
(def bulk-status ::bulk-status)
(def bulk-move ::bulk-move)

(def panel ::panel)
(def history ::history)

(def delete ::delete)
